export const POSITION_1 = {
  rightFootCenterX: 0,
  rightFootCenterZ: 0,
  rightFootCenterY: 0,
  leftFootCenterX: 0,
  leftFootCenterZ: 0,
  leftFootCenterY: 0,
  centerZ: 0,
  rightX: 0,
  rightY: 0,
  rightZ: 0,
  leftX: 0,
  leftY: 0,
  leftZ: 0,
};
